[MOD] (ALL) Totally rewritten widgets logic [MOD] (MSW) Widgets does not work after this commint, they will work again on the next one [MOD] (UNX) Improved autotools/makefile configuration [ADD] (GTK2) Implemented basic windowing facility [ADD] (GTK2) Implemented xFrame, xButton

diff --git a/current/configure b/current/configure
--- a/current/configure
+++ b/current/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB CXXCPP EGREP ENABLE_WIDGETS_TRUE ENABLE_WIDGETS_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB PKG_CONFIG ac_pt_PKG_CONFIG WIDGETSDEPS_CFLAGS WIDGETSDEPS_LIBS CXXCPP EGREP USE_WIDGETS_TRUE USE_WIDGETS_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -721,13 +721,13 @@ echo X"$0" |
   	  /^X\(\/\).*/{ s//\1/; q; }
   	  s/.*/./; q'`
   srcdir=$ac_confdir
-  if test ! -r "$srcdir/$ac_unique_file"; then
+  if test ! -r $srcdir/$ac_unique_file; then
     srcdir=..
   fi
 else
   ac_srcdir_defaulted=no
 fi
-if test ! -r "$srcdir/$ac_unique_file"; then
+if test ! -r $srcdir/$ac_unique_file; then
   if test "$ac_srcdir_defaulted" = yes; then
     { echo "$as_me: error: cannot find sources ($ac_unique_file) in $ac_confdir or .." >&2
    { (exit 1); exit 1; }; }
@@ -736,7 +736,7 @@ if test ! -r "$srcdir/$ac_unique_file"; then
    { (exit 1); exit 1; }; }
   fi
 fi
-(cd $srcdir && test -r "./$ac_unique_file") 2>/dev/null ||
+(cd $srcdir && test -r ./$ac_unique_file) 2>/dev/null ||
   { echo "$as_me: error: sources are in $srcdir, but \`cd $srcdir' does not work" >&2
    { (exit 1); exit 1; }; }
 srcdir=`echo "$srcdir" | sed 's%\([^\\/]\)[\\/]*$%\1%'`
@@ -768,6 +768,18 @@ ac_env_CPPFLAGS_set=${CPPFLAGS+set}
 ac_env_CPPFLAGS_value=$CPPFLAGS
 ac_cv_env_CPPFLAGS_set=${CPPFLAGS+set}
 ac_cv_env_CPPFLAGS_value=$CPPFLAGS
+ac_env_PKG_CONFIG_set=${PKG_CONFIG+set}
+ac_env_PKG_CONFIG_value=$PKG_CONFIG
+ac_cv_env_PKG_CONFIG_set=${PKG_CONFIG+set}
+ac_cv_env_PKG_CONFIG_value=$PKG_CONFIG
+ac_env_WIDGETSDEPS_CFLAGS_set=${WIDGETSDEPS_CFLAGS+set}
+ac_env_WIDGETSDEPS_CFLAGS_value=$WIDGETSDEPS_CFLAGS
+ac_cv_env_WIDGETSDEPS_CFLAGS_set=${WIDGETSDEPS_CFLAGS+set}
+ac_cv_env_WIDGETSDEPS_CFLAGS_value=$WIDGETSDEPS_CFLAGS
+ac_env_WIDGETSDEPS_LIBS_set=${WIDGETSDEPS_LIBS+set}
+ac_env_WIDGETSDEPS_LIBS_value=$WIDGETSDEPS_LIBS
+ac_cv_env_WIDGETSDEPS_LIBS_set=${WIDGETSDEPS_LIBS+set}
+ac_cv_env_WIDGETSDEPS_LIBS_value=$WIDGETSDEPS_LIBS
 ac_env_CXXCPP_set=${CXXCPP+set}
 ac_env_CXXCPP_value=$CXXCPP
 ac_cv_env_CXXCPP_set=${CXXCPP+set}
@@ -853,6 +865,8 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-maintainer-mode  enable make rules and dependencies not useful
+			  (and sometimes confusing) to the casual installer
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-debug		Turn on debugging
@@ -865,6 +879,11 @@ Some influential environment variables:
               nonstandard directory <lib dir>
   CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
               headers in a nonstandard directory <include dir>
+  PKG_CONFIG  path to pkg-config utility
+  WIDGETSDEPS_CFLAGS
+              C compiler flags for WIDGETSDEPS, overriding pkg-config
+  WIDGETSDEPS_LIBS
+              linker flags for WIDGETSDEPS, overriding pkg-config
   CXXCPP      C++ preprocessor
 
 Use these variables to override the choices made by `configure' or to help
@@ -1807,6 +1826,32 @@ host_vendor=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
 host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 
+echo "$as_me:$LINENO: checking whether to enable maintainer-specific portions of Makefiles" >&5
+echo $ECHO_N "checking whether to enable maintainer-specific portions of Makefiles... $ECHO_C" >&6
+    # Check whether --enable-maintainer-mode or --disable-maintainer-mode was given.
+if test "${enable_maintainer_mode+set}" = set; then
+  enableval="$enable_maintainer_mode"
+  USE_MAINTAINER_MODE=$enableval
+else
+  USE_MAINTAINER_MODE=no
+fi;
+  echo "$as_me:$LINENO: result: $USE_MAINTAINER_MODE" >&5
+echo "${ECHO_T}$USE_MAINTAINER_MODE" >&6
+
+
+if test $USE_MAINTAINER_MODE = yes; then
+  MAINTAINER_MODE_TRUE=
+  MAINTAINER_MODE_FALSE='#'
+else
+  MAINTAINER_MODE_TRUE='#'
+  MAINTAINER_MODE_FALSE=
+fi
+
+  MAINT=$MAINTAINER_MODE_TRUE
+
+
+
+
 
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -2732,6 +2777,208 @@ else
   RANLIB="$ac_cv_prog_RANLIB"
 fi
 
+
+
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+
+if test -n "$PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_ac_pt_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+
+if test -n "$ac_pt_PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $ac_pt_PKG_CONFIG" >&5
+echo "${ECHO_T}$ac_pt_PKG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  PKG_CONFIG=$ac_pt_PKG_CONFIG
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.9.0
+	echo "$as_me:$LINENO: checking pkg-config is at least version $_pkg_min_version" >&5
+echo $ECHO_N "checking pkg-config is at least version $_pkg_min_version... $ECHO_C" >&6
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	else
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+		PKG_CONFIG=""
+	fi
+
+fi
+
+pkg_failed=no
+echo "$as_me:$LINENO: checking for WIDGETSDEPS_CFLAGS" >&5
+echo $ECHO_N "checking for WIDGETSDEPS_CFLAGS... $ECHO_C" >&6
+if test "${pkg_cv_WIDGETSDEPS_CFLAGS+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "x$ac_cv_env_WIDGETSDEPS_CFLAGS_set" = "xset"; then
+	pkg_cv_WIDGETSDEPS_CFLAGS=$ac_cv_env_WIDGETSDEPS_CFLAGS_value
+elif test -n "$PKG_CONFIG"; then
+	if { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists \"gtk+-2.0 >= 2.2 glib-2.0 >= 2.2\" >/dev/null 2>&1") >&5
+  ($PKG_CONFIG --exists "gtk+-2.0 >= 2.2 glib-2.0 >= 2.2" >/dev/null 2>&1) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+		pkg_cv_WIDGETSDEPS_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.2 glib-2.0 >= 2.2" 2>/dev/null`
+	else
+		pkg_failed=yes
+	fi
+else
+	pkg_failed=untried
+fi
+fi
+echo "$as_me:$LINENO: result: $pkg_cv_WIDGETSDEPS_CFLAGS" >&5
+echo "${ECHO_T}$pkg_cv_WIDGETSDEPS_CFLAGS" >&6
+echo "$as_me:$LINENO: checking for WIDGETSDEPS_LIBS" >&5
+echo $ECHO_N "checking for WIDGETSDEPS_LIBS... $ECHO_C" >&6
+if test "${pkg_cv_WIDGETSDEPS_LIBS+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "x$ac_cv_env_WIDGETSDEPS_LIBS_set" = "xset"; then
+	pkg_cv_WIDGETSDEPS_LIBS=$ac_cv_env_WIDGETSDEPS_LIBS_value
+elif test -n "$PKG_CONFIG"; then
+	if { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists \"gtk+-2.0 >= 2.2 glib-2.0 >= 2.2\" >/dev/null 2>&1") >&5
+  ($PKG_CONFIG --exists "gtk+-2.0 >= 2.2 glib-2.0 >= 2.2" >/dev/null 2>&1) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+		pkg_cv_WIDGETSDEPS_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.2 glib-2.0 >= 2.2" 2>/dev/null`
+	else
+		pkg_failed=yes
+	fi
+else
+	pkg_failed=untried
+fi
+fi
+echo "$as_me:$LINENO: result: $pkg_cv_WIDGETSDEPS_LIBS" >&5
+echo "${ECHO_T}$pkg_cv_WIDGETSDEPS_LIBS" >&6
+
+if test $pkg_failed = yes; then
+	WIDGETSDEPS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 >= 2.2 glib-2.0 >= 2.2"`
+	# Put the nasty error message in config.log where it belongs
+	echo "$WIDGETSDEPS_PKG_ERRORS" 1>&5
+
+	{ { echo "$as_me:$LINENO: error: Package requirements (gtk+-2.0 >= 2.2 glib-2.0 >= 2.2) were not met.
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively you may set the WIDGETSDEPS_CFLAGS and WIDGETSDEPS_LIBS environment variables
+to avoid the need to call pkg-config.  See the pkg-config man page for
+more details." >&5
+echo "$as_me: error: Package requirements (gtk+-2.0 >= 2.2 glib-2.0 >= 2.2) were not met.
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively you may set the WIDGETSDEPS_CFLAGS and WIDGETSDEPS_LIBS environment variables
+to avoid the need to call pkg-config.  See the pkg-config man page for
+more details." >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively you may set the WIDGETSDEPS_CFLAGS and WIDGETSDEPS_LIBS environment variables
+to avoid the need to call pkg-config.  See the pkg-config man page for
+more details.
+
+To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+See \`config.log' for more details." >&5
+echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively you may set the WIDGETSDEPS_CFLAGS and WIDGETSDEPS_LIBS environment variables
+to avoid the need to call pkg-config.  See the pkg-config man page for
+more details.
+
+To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	WIDGETSDEPS_CFLAGS=$pkg_cv_WIDGETSDEPS_CFLAGS
+	WIDGETSDEPS_LIBS=$pkg_cv_WIDGETSDEPS_LIBS
+	:
+fi
 
 
 
@@ -3689,7 +3936,6 @@ _ACEOF
 
 
 
-
 case $host in
   *-*-mingw32* | *-*-windows*)
     CXXFLAGS="$CXXFLAGS -D__WINDOWS__"
@@ -3699,25 +3945,27 @@ case $host in
     ;;
 esac
 
+CFLAGS="`echo $CFLAGS | sed "s/-fomit-frame-pointer//g"`"
+CXXFLAGS="`echo $CXXFLAGS | sed "s/-fomit-frame-pointer//g"`"
 
+CXXFLAGS="$CXXFLAGS -frtti -fexceptions"
 
 
 # Check whether --enable-debug or --disable-debug was given.
 if test "${enable_debug+set}" = set; then
   enableval="$enable_debug"
   USE_DEBUG="$enableval"
+else
+  USE_DEBUG="no"
 fi;
 # Check whether --enable-widgets or --disable-widgets was given.
 if test "${enable_widgets+set}" = set; then
   enableval="$enable_widgets"
   USE_WIDGETS="$enableval"
+else
+  USE_WIDGETS="no"
 fi;
 
-
-CFLAGS="`echo $CFLAGS | sed "s/-fomit-frame-pointer//g"`"
-CXXFLAGS="`echo $CXXFLAGS | sed "s/-fomit-frame-pointer//g"`"
-
-CXXFLAGS="$CXXFLAGS -frtti -fexceptions"
 
 case "$USE_DEBUG" in
 yes)	DEBUG_FLAGS="-Wall -Wno-unused-parameter -g -D__DEBUG__"
@@ -3734,28 +3982,27 @@ yes)	DEBUG_FLAGS="-Wall -Wno-unused-parameter -g -D__DEBUG__"
 esac
 
 
+case "$USE_WIDGETS" in
+yes)	CXXFLAGS="$CXXFLAGS -D__WIDGETS__" ;;
+*)		CXXFLAGS="$CXXFLAGS" ;;
+esac
 
 
-if test "$USE_WIDGETS"=yes; then
-  ENABLE_WIDGETS_TRUE=
-  ENABLE_WIDGETS_FALSE='#'
+if test x$USE_WIDGETS=xyes; then
+  USE_WIDGETS_TRUE=
+  USE_WIDGETS_FALSE='#'
 else
-  ENABLE_WIDGETS_TRUE='#'
-  ENABLE_WIDGETS_FALSE=
+  USE_WIDGETS_TRUE='#'
+  USE_WIDGETS_FALSE=
 fi
 
-case "$USE_WIDGETS" in
-yes)	CXXFLAGS="$CXXFLAGS -D__WIDGETS__"
-		;;
-*)		CXXFLAGS="$CXXFLAGS"
-		;;
-esac
 
 CXXFLAGS="$CXXFLAGS $DEBUG_FLAGS"
 
+
           ac_config_headers="$ac_config_headers config.h"
 
-                                                                                ac_config_files="$ac_config_files Makefile src/Makefile src/base/Makefile src/widgets/Makefile include/Makefile include/xtk/Makefile include/xtk/base/Makefile include/xtk/widgets/Makefile"
+                                                                                                              ac_config_files="$ac_config_files Makefile src/Makefile src/base/Makefile src/widgets/Makefile src/widgets/gtk2/Makefile include/Makefile include/xtk/Makefile include/xtk/base/Makefile include/xtk/widgets/Makefile xtkbase.pc xtkwidgets.pc"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -3848,6 +4095,13 @@ LIBOBJS=$ac_libobjs
 LTLIBOBJS=$ac_ltlibobjs
 
 
+if test -z "${MAINTAINER_MODE_TRUE}" && test -z "${MAINTAINER_MODE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MAINTAINER_MODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MAINTAINER_MODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -3862,10 +4116,10 @@ echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${ENABLE_WIDGETS_TRUE}" && test -z "${ENABLE_WIDGETS_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_WIDGETS\" was never defined.
+if test -z "${USE_WIDGETS_TRUE}" && test -z "${USE_WIDGETS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_WIDGETS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"ENABLE_WIDGETS\" was never defined.
+echo "$as_me: error: conditional \"USE_WIDGETS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4317,10 +4571,13 @@ do
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "src/base/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/base/Makefile" ;;
   "src/widgets/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/widgets/Makefile" ;;
+  "src/widgets/gtk2/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/widgets/gtk2/Makefile" ;;
   "include/Makefile" ) CONFIG_FILES="$CONFIG_FILES include/Makefile" ;;
   "include/xtk/Makefile" ) CONFIG_FILES="$CONFIG_FILES include/xtk/Makefile" ;;
   "include/xtk/base/Makefile" ) CONFIG_FILES="$CONFIG_FILES include/xtk/base/Makefile" ;;
   "include/xtk/widgets/Makefile" ) CONFIG_FILES="$CONFIG_FILES include/xtk/widgets/Makefile" ;;
+  "xtkbase.pc" ) CONFIG_FILES="$CONFIG_FILES xtkbase.pc" ;;
+  "xtkwidgets.pc" ) CONFIG_FILES="$CONFIG_FILES xtkwidgets.pc" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -4438,6 +4695,9 @@ s,@host@,$host,;t t
 s,@host_cpu@,$host_cpu,;t t
 s,@host_vendor@,$host_vendor,;t t
 s,@host_os@,$host_os,;t t
+s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
+s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
+s,@MAINT@,$MAINT,;t t
 s,@CXX@,$CXX,;t t
 s,@CXXFLAGS@,$CXXFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
@@ -4456,10 +4716,14 @@ s,@am__fastdepCXX_TRUE@,$am__fastdepCXX_TRUE,;t t
 s,@am__fastdepCXX_FALSE@,$am__fastdepCXX_FALSE,;t t
 s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
+s,@PKG_CONFIG@,$PKG_CONFIG,;t t
+s,@ac_pt_PKG_CONFIG@,$ac_pt_PKG_CONFIG,;t t
+s,@WIDGETSDEPS_CFLAGS@,$WIDGETSDEPS_CFLAGS,;t t
+s,@WIDGETSDEPS_LIBS@,$WIDGETSDEPS_LIBS,;t t
 s,@CXXCPP@,$CXXCPP,;t t
 s,@EGREP@,$EGREP,;t t
-s,@ENABLE_WIDGETS_TRUE@,$ENABLE_WIDGETS_TRUE,;t t
-s,@ENABLE_WIDGETS_FALSE@,$ENABLE_WIDGETS_FALSE,;t t
+s,@USE_WIDGETS_TRUE@,$USE_WIDGETS_TRUE,;t t
+s,@USE_WIDGETS_FALSE@,$USE_WIDGETS_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
@@ -5177,3 +5441,14 @@ if test "$no_create" != yes; then
   $ac_cs_success || { (exit 1); exit 1; }
 fi
 
+
+
+echo
+echo "  Configured xtklib for '${host}'."
+echo
+echo "  xtklib enabled options:"
+echo
+echo "  Prefix where xtklib should be installed                    ${prefix:-none}"
+echo "  xtklib compibled in debug mode?                            ${USE_DEBUG:-no}"
+echo "  Widgets module enabled?                                    ${USE_WIDGETS:-no}"
+echo
